version: '3'
services:
  payment-service:
    build: .
    ports:
    - "8000:8000"
    links:
    - redis
    volumes:
    - ./app:/app
    environment:
    - PAYPAL_MODE=${PAYPAL_MODE}
    - PAYPAL_CLIENT_ID=${PAYPAL_CLIENT_ID}
    - PAYPAL_CLIENT_SECRET=${PAYPAL_CLIENT_SECRET}
  redis:
    image: redis:alpine
    ports:
    - "6379:6379"