version: '3'
services:
  payment-service:
    build: .
    ports:
    - "8000:8000"
    links:
    - redis
    volumes:
    - ./app:/app
    environment:
    - PAYPAL_MODE=${PAYPAL_MODE}
    - PAYPAL_CLIENT_ID=${PAYPAL_CLIENT_ID}
    - PAYPAL_CLIENT_SECRET=${PAYPAL_CLIENT_SECRET}
    - BRAINTREE_MERCHANT_ID=${BRAINTREE_MERCHANT_ID}
    - BRAINTREE_PUBLIC_KEY=${BRAINTREE_PUBLIC_KEY}
    - BRAINTREE_PRIVATE_KEY=${BRAINTREE_PRIVATE_KEY}
    - NODE_ENV=development
    command: >
      sh -c 'yarn install && yarn run start'
  redis:
    image: redis:alpine
    ports:
    - "6379:6379"